# Generated by Django 5.1 on 2024-09-18 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_customuser_is_superadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_superadmin',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
