# Generated by Django 5.1 on 2024-09-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_remove_customuser_is_superadmin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='purchase_date',
            field=models.DateField(auto_now=True),
        ),
    ]
